package org.choongang.member.constants;

public enum Belonging {
    NATURAL_SCIENCES,
    ENGINEERING_TECHNOLOGY,
    MEDICAL_HEALTH_SCIENCES,
    HUMANITIES,
    SOCIAL_SCIENCES,
    AGRICULTURAL_SCIENCES,
    BUSINESS_ECONOMICS,
    ART_DESIGN
}
